#!/bin/bash
####
# Usage: ./runact device actconfig resultfile
# e.g. ./runact /dev/sdc actconfig_1x.txt sdc-1x-intel320.txt
####
echo "Zero and salt drive"
date
sudo ./actprep $1
echo "Start act"
date
sudo ./act $2 > $3
