#!/bin/sh

if [ $(id -u) -ne 0 ]; then
  echo "This script must be run as root or sudo."
  exit 1
fi

set +e #continue on any errors

#Work with EL/Deb
apt-get -y install make gcc libc6-dev libssl-dev zlib1g-dev || yum install -y make gcc openssl-devel sysstat git 
cd /opt
#git clone https://github.com/brendangregg/perf-tools.git
git clone https://github.com/aerospike/act.git
#export PATH="$PATH:/opt/perf-tools"
cd /opt/act
make
make -f Makesalt

echo "ACT built at /opt/act. Use "act_make_configs.rb" to build config files in cwd."
