# Build ACT rpm distribution.

export RPM_SOURCE_ROOT = $(shell echo `pwd`/dist)
export RPM_BUILD_ROOT = $(RPM_SOURCE_ROOT)/BUILD
export CL_BASE = $(RPM_BUILD_ROOT)/opt/aerospike
export ETC_BASE = $(RPM_BUILD_ROOT)/etc/aerospike

MANIFEST_DIR = manifest/TEMP
DIR_PKG = target/packages
# Version (bare x.y on master; git-describe with SHA on dev branches). RPM Version
# forbids '-', so map it to '_'. The build number (build/version -r, 1-based so the
# tagged release and dev builds are 1) is the Release.
REV = $(shell build/version -v | sed 's/-/_/g')
BUILD_NUMBER = $(shell build/version -r)
BLD_ID = $(shell git describe 2>/dev/null; if [ $${?} != 0 ]; then echo 'unknown'; fi)
OS = $(shell build/os_version)
ARCH=$(shell uname -m)

.PHONY: default
default: dist
	mkdir -p $(DIR_PKG)
	mkdir -p $(RPM_BUILD_ROOT)
	mkdir -p $(RPM_SOURCE_ROOT)/RPMS/x86_64
	mkdir -p $(RPM_BUILD_ROOT)/usr/bin

	sed 's/@VERSION@/'$(REV)'/g' <pkg/rpm/act.spec >pkg/act_v.spec
	sed -i 's/@RELEASE@/'$(BUILD_NUMBER)'/g' pkg/act_v.spec
	sed -i 's/@ARCH@/'$(ARCH)'/g' pkg/act_v.spec

	rpmbuild --noclean -bb -vv --define "dist .$(OS)" --buildroot $(RPM_BUILD_ROOT) pkg/act_v.spec
	find $(RPM_SOURCE_ROOT)/RPMS -type f -exec mv {} $(DIR_PKG) \;
	rm -rf pkg/act_v.spec dist

distclean:
	rm -rf $(RPM_BUILD_ROOT)
	rm -rf target/packages:

.PHONY: dist
dist:

	mkdir -p $(CL_BASE)
	mkdir -p $(ETC_BASE)
	mkdir -p $(CL_BASE)/bin

	# act
	install -m 755 target/bin/act_* $(CL_BASE)/bin/
	install -m 755 analysis/act_latency.py $(CL_BASE)/bin/
	install -m 755 config/act_index.conf $(ETC_BASE)/
	install -m 755 config/act_storage.conf $(ETC_BASE)/

print-% : ; @echo $($*)
