name: Build ACT

on:
  workflow_dispatch:
        
jobs:
  buils_debian_x86_64:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        container: [ 'debian:10', 'debian:11' ]
    container:
      image: ${{ matrix.container }}
      options: "--entrypoint /bin/bash"
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1 # v2.21.1
      with:
        egress-policy: audit

    - name: Install Dependencies (Debian)
      run: |
        apt-get -y update
        apt-get -y install make gcc libc6-dev git build-essential

    - name: Clone Source
      run: git clone  https://github.com/aerospike/act.git
      
    - name: build act (debian)
      working-directory: ./act
      run: |
        echo "REV=$(make -f pkg/Makefile.deb print-REV)" >> $GITHUB_ENV
        echo "OS=$(make -f pkg/Makefile.deb print-OS)" >> $GITHUB_ENV
        echo "ARCH=$(make -f pkg/Makefile.deb print-ARCH)" >> $GITHUB_ENV
        echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-6)" >> $GITHUB_ENV        
        make all deb      

    - name: Upload Artifacts
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: act_${{ env.REV }}-1${{ env.OS }}_${{ env.ARCH }}.deb
        path: /__w/act/act/act/target/packages/act_*
        if-no-files-found: error
 
  build_ubuntu_x86_64:
    strategy:
      matrix:
        os: [ 'ubuntu-20.04', 'ubuntu-18.04' ]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1 # v2.21.1
      with:
        egress-policy: audit

    - name: Install Dependencies
      run: sudo apt-get install make gcc libc6-dev

    - name: Get Sources
      uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      with:
        fetch-depth: 0

    - name: Set env
      run: |
        echo "REV=$(make -f pkg/Makefile.deb print-REV)" >> $GITHUB_ENV
        echo "OS=$(make -f pkg/Makefile.deb print-OS)" >> $GITHUB_ENV
        echo "ARCH=$(make -f pkg/Makefile.deb print-ARCH)" >> $GITHUB_ENV
        echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-6)" >> $GITHUB_ENV

    - name: build
      run: make all deb

    - name: Upload Artifact
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with: 
        name: act_${{ env.REV }}-1${{ env.OS }}_${{ env.ARCH }}.deb
        path: target/packages
        if-no-files-found: error
